### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by pwmarcz**

### CODE REVIEW

**Comment by marmarek** [comment]
I've added test coverage measuring also for C code (and fixed the python one) in #22.
If you're interested in coverage numbers with this PR merged, see here: https://codecov.io/gh/marmarek/qubes-core-qrexec/commit/ac0eaaaeb84e11d3691694fb86e1bde068b4d29c

**Comment by pwmarcz** [comment]
Looks great!
`qrexec-daemon.c` is missing from the coverage, though. I'm not sure why, it's being killed wih SIGTERM but so is `qrexec-agent`.

**Comment by marmarek** [comment]
I think that's it. With trivial SIGTERM handler (`exit(0)`) it works: https://codecov.io/gh/marmarek/qubes-core-qrexec/commit/b6a5811e1225324269967caff13ce0a5a1136bb4
This may mean coverage data for qrexec-agent is incomplete.

**Comment by marmarek** [comment]
@pwmarcz can you add also a test for `qrexec-client -d domain -l local_cmd user:remote_cmd`? It will ease debugging current failure in #3.

**Comment by pwmarcz** [comment]
Added one.

**Pull request merged**
