### PR TITLE
Support additional policy directories

### PR DESCRIPTION
**Pull request by DemiMarie**
This allows multiple directories to contain qrexec policy, which allows for transient policy that disappears on reboot.

Fixes: QubesOS/qubes-issues#8513

### CODE REVIEW

**Comment by marmarek** [comment]
I don't think keeping (some) policy in user home is a good idea. Better approach is to extend backup to include additional files/directories.

**Comment by marmarek** [comment]
This needs a rebase now (probably simply dropping the https://github.com/QubesOS/qubes-core-qrexec/pull/134/commits/0bc884a34888251e57b1c50e61a0a490c3e1c94c commit, as #160 got merged)

**Comment by marmarek** [comment]
Pylint complains, looks like an import got lost in rebase.

**Comment by marmarek** [comment]
A conflict on tests...

**Comment by marmarek** [comment]
ping (doc update)?

**Comment by DemiMarie** [comment]
@marmarek: QubesOS/qubes-doc#1427

**Pull request merged**
