### PR TITLE
Miscellaneous cleanups and bug fixes

### PR DESCRIPTION
**Pull request by DemiMarie**
These are all minor, backportable changes.  All should be self-contained, but cherry-picking individual patches might result in artificial conflicts.

Fixes: QubesOS/qubes-issues#9161.

### CODE REVIEW

**Comment by marmarek** [comment]
> @DemiMarie
[Report "cannot execute" with exit status 126](https://github.com/QubesOS/qubes-core-qrexec/pull/137/commits/e0043a476af79907692946c7cae0a7af7e31bf63)

We use code 126 for "request refused". I think it's okay to consider "service not found" as "request refused" too, but lets try not to conflate too many runtime errors into this one (especially, temporary errors preferably should use a different code).

**Comment by DemiMarie** [comment]
> > @DemiMarie
> > [Report "cannot execute" with exit status 126](https://github.com/QubesOS/qubes-core-qrexec/pull/137/commits/e0043a476af79907692946c7cae0a7af7e31bf63)
> 
> We use code 126 for "request refused". I think it's okay to consider "service not found" as "request refused" too, but lets try not to conflate too many runtime errors into this one (especially, temporary errors preferably should use a different code).

What about using 137, SIGKILL?

**Comment by marmarek** [comment]
> What about using 137, SIGKILL?

Sounds even more confusing (could be, rightfully, interpreted as service was started, and then killed).

**Comment by DemiMarie** [comment]
> > What about using 137, SIGKILL?
> 
> Sounds even more confusing (could be, rightfully, interpreted as service was started, and then killed).

`sysexits.h` codes then?

**Comment by marmarek** [comment]
Can be. But also, I think from practical point of view, it's better to have a _single_ exit code for "call was allowed, service exists but failed to start for any reason", and log more details. There is no point of using different exit codes for different failure modes, as those are not really interesting for the calling side and increase risk of clashing with exit code used by the service itself.

**Comment by DemiMarie** [comment]
That makes sense, but whatever is chosen should certainly be in a `.h` file and not repeated a few dozen times.

**Comment by DemiMarie** [comment]
PipelineRetryFailed

**Comment by marmarek** [comment]
> * TC_20_USBProxy_core3_fedora-39-xfce: [test_070_attach_not_installed_front](https://openqa.qubes-os.org/tests/97772#step/TC_20_USBProxy_core3_fedora-39-xfce/9) (error)
>       `qubesusbproxy.core3ext.QubesUSBException: Device attach failed:`

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 342, in on_device_attach_usb
    await vm.run_service_for_stdio('qubes.USBAttach',
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1576, in run_service_for_stdio
    raise subprocess.CalledProcessError(p.returncode,
subprocess.CalledProcessError: Command 'qubes.USBAttach' returned non-zero exit status 125.
```
This should be 127, the test removes `/etc/qubes-rpc/qubes.USBAttach`

**Review by marmarek — APPROVED** [review]

**Pull request merged**
